name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      label:
        required: false
        default: "latest"
        type: string
      path:
        required: false
        default: "./"
        type: string
      owner:
        required: true
        type: string
      push:
        required: false
        default: true
        type: boolean
      registry:
        required: false
        default: "ghcr.io"
        type: string
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delete Old Images
        if: ${{ inputs.push }}
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
          keep-n-tagged: 2
          exclude-tags: latest
          package: ${{ inputs.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Log Into GHCR
        if: ${{ inputs.push }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ inputs.registry }}/${{ inputs.owner }}/${{ inputs.name }}
          tags: |
            type=raw,value=${{ inputs.label }}

      - name: Build And Push Image
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: ${{ inputs.path }}
          file: ${{ inputs.path }}/Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
