name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      label:
        required: true
        type: string
      path:
        required: false
        default: "./"
        type: string
      owner:
        required: true
        type: string
      push:
        required: false
        default: true
        type: boolean
      registry:
        required: false
        default: "ghcr.io"
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delete Old Images
        if: ${{ inputs.push }}
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
          package: ${{ inputs.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log Into GHCR
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.owner }}/${{ inputs.name }}

      - name: Build And Push Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.path }}
          file: ${{ inputs.path }}/Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
