name: Reusable Docker Buildscript
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      label:
        required: false
        default: "latest"
        type: string
      path:
        required: false
        default: "./"
        type: string
      owner:
        required: true
        type: string
      push:
        required: false
        default: true
        type: boolean
      registry:
        required: false
        default: "ghcr.io"
        type: string
      platforms:
        required: false
        default: "linux/amd64"
        type: string
      rotate:
        required: false
        default: true
        type: boolean
concurrency:
  group: docker-${{ inputs.owner }}-${{ inputs.name }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Log into GHCR
        if: ${{ inputs.push }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ inputs.registry }}/${{ inputs.owner }}/${{ inputs.name }}
          tags: |
            type=raw,value=${{ inputs.label }}
            type=raw,value=latest

      - name: Build and push multi-platform image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ inputs.path }}
          file: ${{ inputs.path }}/Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ inputs.platforms }}

      - name: Delete old images
        if: ${{ inputs.push && inputs.rotate }}
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-untagged: 1
          keep-n-tagged: 2
          exclude-tags: latest
          package: ${{ inputs.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
